<?php

namespace ArtesanIO\MoocsyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesRepository extends EntityRepository
{
    public function findCourseUser($course, $user)
    {
        try {
            return $this->getEntityManager()->createQuery(
                    'SELECT cu FROM MoocsyBundle:CoursesUsers cu
                     LEFT JOIN cu.courses c
                     WHERE cu.users = :user
                     AND c.slug = :course
                    '
            )
            ->setParameter('course', $course->getSlug())
            ->setParameter('user', $user)
            ->getSingleResult()
            ;

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findCoursesUser($user)
    {
        try {
            return $this->getEntityManager()->createQuery(
                    'SELECT cu FROM MoocsyBundle:CoursesUsers cu
                     WHERE cu.users = :user
                    '
            )
            ->setParameter('user', $user)
            ->getResult()
            ;

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
