<?php

namespace ArtesanIO\MoocsyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends EntityRepository
{

    public function findOneItemModuleCourse($course, $module, $item)
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    'SELECT i FROM ArtesanIO\MoocsyBundle\Entity\Items i
                    LEFT JOIN i.modules m
                    LEFT JOIN m.courses c
                    WHERE i.slug = :item
                    AND m.slug   = :module
                    AND c.slug   = :course
                    '
                )
                ->setParameter('item', $item)
                ->setParameter('module', $module)
                ->setParameter('course', $course)
                ->getSingleResult()
            ;

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
