<?php

namespace ArtesanIO\MoocsyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemsQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsQuizRepository extends EntityRepository
{

    function findQuizItemModuleCourse($quiz, $item, $module, $course)
    {

        $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT iq FROM MoocsyBundle:ItemsQuiz iq
                     LEFT JOIN iq.items i
                     LEFT JOIN i.modules m
                     LEFT JOIN m.courses c
                     WHERE iq.id = :quiz
                     AND i.slug = :item
                     AND m.slug = :module
                     AND c.slug = :course
                    '
                )
                ->setParameter('quiz', $quiz)
                ->setParameter('item', $item)
                ->setParameter('module', $module)
                ->setParameter('course', $course)
        ;

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }

}
