<?php

namespace ArtesanIO\MoocsyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulesRepository extends EntityRepository
{

    public function findOneModuleCourse($course, $module)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM ArtesanIO\MoocsyBundle\Entity\Modules m
                LEFT JOIN m.courses c
                WHERE m.slug = :module
                AND c.slug   = :course
                '
            )
            ->setParameter('module', $module)
            ->setParameter('course', $course)
            ->getSingleResult()
        ;
    }

}
