<?php

namespace ArtesanIO\MoocsyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsRepository extends EntityRepository
{
    function findUserNotifications($id)
    {
        $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT n FROM MoocsyBundle:Notifications n
                     WHERE n.users  = :user
                     ORDER BY n.id DESC
                    '
                )
                ->setParameter('user', $id)
        ;

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findNotificationsUnanswered()
    {
        try {
            return $this->getEntityManager()->createQuery(
                'SELECT n FROM MoocsyBundle:Notifications n
                 WHERE n.state = 0
                 AND n.requestResponse = 1
                 ORDER BY n.id DESC
                '
            )
            ->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }

    public function findNotificationsAnswered()
    {
        try {
            return $this->getEntityManager()->createQuery(
                'SELECT n FROM MoocsyBundle:Notifications n
                 WHERE n.state = 1
                 AND n.requestResponse = 1
                 ORDER BY n.id DESC
                '
            )
            ->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }

}
