<?php

namespace ArtesanIO\MoocsyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends EntityRepository
{
    function findQuestionQuizItemModuleCourse($question, $quiz, $item, $module, $course)
    {

        $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT q FROM MoocsyBundle:Questions q
                     LEFT JOIN q.itemsQuiz iq
                     LEFT JOIN iq.items i
                     LEFT JOIN i.modules m
                     LEFT JOIN m.courses c
                     WHERE q.id  = :question
                     AND iq.id   = :quiz
                     AND i.slug  = :item
                     AND m.slug  = :module
                     AND c.slug  = :course
                    '
                )
                ->setParameter('question', $question)
                ->setParameter('quiz', $quiz)
                ->setParameter('item', $item)
                ->setParameter('module', $module)
                ->setParameter('course', $course)
        ;

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
