<?php

namespace ArtesanIO\MoocsyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizDetailsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizDetailsUserRepository extends EntityRepository
{
    function findOptionsQuestionQuiz($quiz)
    {
        try {

        return $this->getEntityManager()
                ->createQuery(
                    'SELECT o FROM MoocsyBundle:QuizDetailsUser o
                     LEFT JOIN o.questions q
                     LEFT JOIN q.itemsQuiz iQ
                     WHERE iQ.id  = :quiz
                    '
                )
                ->setParameter('quiz', $quiz)
                ->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            
            return null;
        }

    }

}
